vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        products:
            uri_prefix: /uploads/products
            upload_destination: '%kernel.project_dir%/public/uploads/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false
            inject_on_load: false

        category:
            uri_prefix: /uploads/categories
            upload_destination: '%kernel.project_dir%/public/uploads/categories'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            delete_on_update: false
            delete_on_remove: false
            inject_on_load: false
