controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

product_show:
    path: /product/{id}
    controller: App\Controller\ProductController::show
    methods: ['GET']
